name = "ReplicatorMutatorDynamics"
authors = ["Maria Alejandra Ramirez"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
ReplicatorMutatorDynamics = "60519332-4029-4e71-a3e0-4f943c157cd5"

[compat]
DrWatson = "2.9.1"
julia = "1.7.0"
